import './globals.css'
import { Inter, Poor_Story } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeModeScript } from 'flowbite-react'

const inter = Poor_Story({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <head></head>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
